/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 05-dic.-2018 10:26:44 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Compra` CASCADE
;

DROP TABLE IF EXISTS `Inventario` CASCADE
;

DROP TABLE IF EXISTS `Producto` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

DROP TABLE IF EXISTS `Ventas` CASCADE
;

/* Create Tables */

CREATE TABLE `Compra`
(
	`id_compra` VARCHAR(10) NULL,
	`id_producto` INT NOT NULL,
	`precio_compra` FLOAT(0,0) NULL,
	CONSTRAINT `PK_Compra` PRIMARY KEY (`id_producto` ASC)
)

;

CREATE TABLE `Inventario`
(
	`id_producto` INT NOT NULL,
	`cantidad` INT NULL,
	CONSTRAINT `PK_Inventario` PRIMARY KEY (`id_producto` ASC)
)

;

CREATE TABLE `Producto`
(
	`id_producto` INT NOT NULL,
	`nombre_producto` VARCHAR(50) NULL,
	`unidad` VARCHAR(50) NULL,
	`cantidad` FLOAT(0,0) NULL,
	`precio_compra` FLOAT(0,0) NULL,
	`precio_venta` FLOAT(0,0) NULL,
	`departamento` VARCHAR(50) NULL,
	CONSTRAINT `PK_Producto` PRIMARY KEY (`id_producto` ASC)
)

;

CREATE TABLE `Usuario`
(
	`usuario` VARCHAR(20) NULL,
	`password` VARCHAR(20) NULL
)

;

CREATE TABLE `Ventas`
(
	`id_venta` VARCHAR(10) NULL,
	`precio_venta` FLOAT(0,0) NULL,
	`id_producto` INT NOT NULL,
	CONSTRAINT `PK_Ventas` PRIMARY KEY (`id_producto` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Compra` 
 ADD INDEX `IXFK_Compra_Ventas` (`id_producto` ASC)
;

ALTER TABLE `Inventario` 
 ADD INDEX `IXFK_Inventario_Producto` (`id_producto` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Compra` 
 ADD CONSTRAINT `FK_Compra_Ventas`
	FOREIGN KEY (`id_producto`) REFERENCES `Ventas` (`id_producto`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Inventario` 
 ADD CONSTRAINT `FK_Inventario_Producto`
	FOREIGN KEY (`id_producto`) REFERENCES `Producto` (`id_producto`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
