/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 30-nov.-2018 01:30:41 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Compra` CASCADE
;

DROP TABLE IF EXISTS `Inventario` CASCADE
;

DROP TABLE IF EXISTS `Producto` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

DROP TABLE IF EXISTS `Ventas` CASCADE
;

/* Create Tables */

CREATE TABLE `Compra`
(
	`id_compra` VARCHAR(10) NULL,
	`producto` VARCHAR(20) NULL,
	`cantidad` INT NULL,
	`precio` INT NULL
)

;

CREATE TABLE `Inventario`
(
	`id_producto` VARCHAR(50) NOT NULL,
	`cantidad` INT NULL,
	`Nombre` VARCHAR(20) NULL,
	CONSTRAINT `PK_Inventario` PRIMARY KEY (`id_producto` ASC)
)

;

CREATE TABLE `Producto`
(
	`id_producto` VARCHAR(20) NOT NULL,
	`Nombre` VARCHAR(20) NULL,
	`Cantidad` INT NULL,
	`Precio_compra` INT NULL,
	`Precio_venta` INT NULL,
	`Departamento` VARCHAR(20) NULL,
	CONSTRAINT `PK_Producto` PRIMARY KEY (`id_producto` ASC)
)

;

CREATE TABLE `Usuario`
(
	`Usuario` VARCHAR(20) NULL,
	`Password` VARCHAR(20) NULL
)

;

CREATE TABLE `Ventas`
(
	`id_venta` VARCHAR(10) NULL,
	`cantidad` INT NULL,
	`Descripcion` VARCHAR(50) NULL,
	`Precio` INT NULL
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Inventario` 
 ADD INDEX `IXFK_Inventario_Producto` (`id_producto` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Inventario` 
 ADD CONSTRAINT `FK_Inventario_Producto`
	FOREIGN KEY (`id_producto`) REFERENCES `Producto` (`id_producto`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
